In [2]:
import pandas as pd

In [14]:
df = pd.read_csv("train.csv",on_bad_lines='skip',engine='python')

In [15]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [18]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [17]:
df = df.dropna()

In [20]:
inp = df.drop('label',axis=1)

In [21]:
target = df['label']

In [23]:
inp.shape

(8318, 4)

In [25]:
import tensorflow as tf

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [27]:
voc_size = 5000

In [28]:
messages = inp.copy()

In [29]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [30]:
messages.reset_index(inplace=True)

In [31]:
import nltk
import re
from nltk.corpus import stopwords

In [32]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [37]:
#pre-processing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499
3500
3501
3502
3503
3504
3505
3506
3507

In [38]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [39]:
onehot_rep = [one_hot(words, voc_size) for words in corpus]
onehot_rep

[[4608, 1887, 2040, 2012, 1230, 4261, 3845, 436, 4769, 4179],
 [4229, 4208, 3750, 1243, 4470, 1131, 4321],
 [150, 2826, 3709, 3081],
 [4851, 4461, 2539, 1958, 882, 2301],
 [1806, 4470, 875, 4766, 2304, 2891, 4470, 1839, 955, 1467],
 [1788,
  465,
  385,
  3885,
  4058,
  4447,
  1313,
  740,
  1904,
  3832,
  2510,
  1050,
  479,
  1174,
  4321],
 [1668, 4835, 84, 2347, 2734, 2580, 2898, 1735, 4485, 2050, 1471],
 [1636, 997, 4429, 2634, 4953, 990, 4447, 580, 4485, 2050, 1471],
 [2198, 4082, 831, 1030, 967, 1154, 339, 2037, 4447, 1072],
 [2276, 4698, 1747, 1019, 3753, 4163, 3756, 1453],
 [1764, 2628, 2573, 617, 3080, 1394, 598, 2741, 3720, 3616, 164],
 [1958, 1650, 1230, 1154, 4447, 4953],
 [2524, 598, 4208, 2172, 3920, 2615, 2051, 3394, 2758],
 [4815, 3975, 63, 3969, 4500, 4807, 3, 4485, 2050, 1471],
 [4531, 1660, 4750, 2681, 4688, 4485, 2050, 1471],
 [1967, 2758, 4825, 3900, 4201, 2891, 4422, 3442, 1527, 1342],
 [3958, 2673, 4208],
 [2683, 1761, 2253, 2852, 4447, 2218, 4889, 4321],
 [

In [40]:
print(corpus[1])
print(onehot_rep[1])

flynn hillari clinton big woman campu breitbart
[4229, 4208, 3750, 1243, 4470, 1131, 4321]


In [63]:
#embedding
sent_length = 20
emb_doc = pad_sequences(onehot_rep, padding='pre',maxlen=sent_length)
print(emb_doc)

[[   0    0    0 ...  436 4769 4179]
 [   0    0    0 ... 4470 1131 4321]
 [   0    0    0 ... 2826 3709 3081]
 ...
 [   0    0    0 ... 2095 3117 4779]
 [   0    0    0 ... 4447 4863 3964]
 [   0    0    0 ... 1918 4284  341]]


In [42]:
emb_doc[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 4229, 4208, 3750, 1243, 4470, 1131, 4321], dtype=int32)

In [43]:
##applying embedding + LSTM layer
#model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100)) # 100 neurons
model.add(Dense(1,activation='sigmoid')) #since binary classification
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [45]:
target.shape

(8318,)

In [46]:
import numpy as np
X_final = np.array(emb_doc)
y_final = np.array(target)

In [47]:
X_final.shape, y_final.shape

((8318, 20), (8318,))

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final, test_size=0.33,random_state=42)

In [49]:
#Model Training
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10,batch_size=64)

Epoch 1/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.7270 - loss: 0.5367 - val_accuracy: 0.9129 - val_loss: 0.2115
Epoch 2/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9185 - loss: 0.1888 - val_accuracy: 0.9271 - val_loss: 0.1813
Epoch 3/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 7s 53ms/step - accuracy: 0.9560 - loss: 0.1169 - val_accuracy: 0.9257 - val_loss: 0.2021
Epoch 4/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9776 - loss: 0.0733 - val_accuracy: 0.9279 - val_loss: 0.2120
Epoch 5/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - accuracy: 0.9883 - loss: 0.0426 - val_accuracy: 0.9195 - val_loss: 0.2666
Epoch 6/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9963 - loss: 0.0218 - val_accuracy: 0.9209 - val_loss: 0.2493
Epoch 7/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 4s 32ms/step - accuracy: 0.9959 - loss: 0.0211 - val_accuracy: 0.9140 - val_loss: 0.4237
Epoch 8/10
88/88 ━━━━━━━━━━━━━━━━━━━━ 6s 45ms/step - accuracy: 0.9961 - loss: 0.0149 - val_accuracy: 0.9071 - v

In [50]:
#Performance metrics
y_pred = model.predict(X_test)

86/86 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step


In [51]:
y_pred = np.where(y_pred > 0.5, 1, 0)

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [53]:
confusion_matrix(y_test, y_pred)

array([[1449,  112],
       [ 152, 1032]])

In [55]:
accuracy_score(y_test, y_pred)

0.9038251366120219

In [59]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.93      0.92      1561
           1       0.90      0.87      0.89      1184

    accuracy                           0.90      2745
   macro avg       0.90      0.90      0.90      2745
weighted avg       0.90      0.90      0.90      2745



In [80]:
custom_sentence = one_hot("A newly developed MRI scan allows parents to see detailed images of the beating heart of even a",voc_size)
padded_sq = pad_sequences([custom_sentence], padding='pre',maxlen=sent_length)

In [81]:
if model.predict(padded_sq)[0][0] > 0.5:
  print("News (False)")
else:
  print("News (True)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
News (True)


In [82]:
custom_sentence = one_hot("Can I have one girlfriend without you bastards f**king it up? asks Harry",voc_size)
padded_sq = pad_sequences([custom_sentence], padding='pre',maxlen=sent_length)

In [83]:
if model.predict(padded_sq)[0][0] > 0.5:
  print("News (False)")
else:
  print("News (True)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
News (False)
