In [6]:
!pip install tensorflow

In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a god developer',
        'understand the meaning of words',
        'this book is good']

In [9]:
voc_size = 10000

In [10]:
one_hot_rep = [one_hot(words,voc_size) for words in sent]
print(one_hot_rep)

[[6335, 39, 1135, 6986], [6335, 39, 1135, 5622], [6335, 1935, 1135, 2155], [4758, 4839, 9916, 507, 6468], [4758, 4839, 9916, 7877, 3866], [4225, 6335, 5262, 1135, 1785], [1894, 5748, 319, 507]]


In [11]:
#word-emb-rep
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6335   39 1135 6986]
 [   0    0    0    0 6335   39 1135 5622]
 [   0    0    0    0 6335 1935 1135 2155]
 [   0    0    0 4758 4839 9916  507 6468]
 [   0    0    0 4758 4839 9916 7877 3866]
 [   0    0    0 4225 6335 5262 1135 1785]
 [   0    0    0    0 1894 5748  319  507]]


In [25]:
model = Sequential()
model.add(Embedding(voc_size,10,input_shape=(sent_length,)))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [26]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[[-7.46138394e-05,  2.82384492e-02,  3.93276289e-03,
         -1.49006359e-02, -2.24963911e-02, -3.65924835e-03,
         -3.00846584e-02,  4.73893173e-02,  3.71340550e-02,
          1.47625059e-03],
        [-7.46138394e-05,  2.82384492e-02,  3.93276289e-03,
         -1.49006359e-02, -2.24963911e-02, -3.65924835e-03,
         -3.00846584e-02,  4.73893173e-02,  3.71340550e-02,
          1.47625059e-03],
        [-7.46138394e-05,  2.82384492e-02,  3.93276289e-03,
         -1.49006359e-02, -2.24963911e-02, -3.65924835e-03,
         -3.00846584e-02,  4.73893173e-02,  3.71340550e-02,
          1.47625059e-03],
        [-7.46138394e-05,  2.82384492e-02,  3.93276289e-03,
         -1.49006359e-02, -2.24963911e-02, -3.65924835e-03,
         -3.00846584e-02,  4.73893173e-02,  3.71340550e-02,
          1.47625059e-03],
        [ 1.27858408e-02,  1.75595768e-02,  4.95968200e-02,
         -3.84006985e-02,  3.09499614e-02, -1.36853084e-02,
         -3.94051298e-02,  3.28128412e-03, -4.409983

In [31]:
sent=["the world is a better place with you in it",
      "I like both DC and Marvel Franchise",
      "Deadpool and Wolverine movie was really good",
      "She had some amazing news to share",
      "He decided to fake his disappearance to avoid jail",
      "It took him a month to finish the meal"]

In [32]:
one_hot_rep = [one_hot(words,voc_size) for words in sent]
print(one_hot_rep)

[[6335, 2968, 319, 9916, 1980, 6038, 4662, 555, 4890, 509], [4758, 2012, 1287, 8350, 1416, 6509, 726], [5159, 1416, 680, 3132, 4398, 6032, 507], [4016, 7597, 2560, 4107, 4849, 414, 9104], [4787, 6722, 414, 417, 7876, 281, 414, 5749, 1007], [509, 1010, 9070, 9916, 1381, 414, 5062, 6335, 5697]]


In [33]:
sent_length = 12
embedded_docs = pad_sequences(one_hot_rep, padding='post',maxlen=sent_length)
print(embedded_docs)

[[6335 2968  319 9916 1980 6038 4662  555 4890  509    0    0]
 [4758 2012 1287 8350 1416 6509  726    0    0    0    0    0]
 [5159 1416  680 3132 4398 6032  507    0    0    0    0    0]
 [4016 7597 2560 4107 4849  414 9104    0    0    0    0    0]
 [4787 6722  414  417 7876  281  414 5749 1007    0    0    0]
 [ 509 1010 9070 9916 1381  414 5062 6335 5697    0    0    0]]


In [34]:
model.add(Embedding(voc_size,10))
model.compile('adam','mse')

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[[-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         ...,
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972]],

        [[-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         [-0.0017584 ,  0.02493859,  0.0267227 , ..., -0.0443587 ,
           0.02113282, -0.01109972],
         ...,
         [-0.0017584 ,  0.02493859